export const WINDOWS_SIZE = 'WINDOWS_SIZE';
export const DESTINATION_LIST = 'DESTINATION_LIST';
export const DESTINATION_DETAIL = 'DESTINATION_DETAIL';
export const MAP_LIST = 'MAP_LIST';
export const DINING_LIST = 'DINING_LIST';
export const DINING_DETAIL = 'DINING_DETAIL';
export const ACTIVITY_LIST = 'ACTIVITY_LIST';
export const ACTIVITY_DESTINATION_LIST = 'ACTIVITY_DESTINATION_LIST';
export const ACTIVITY_DESTINATION_DETAIL = 'ACTIVITY_DESTINATION_DETAIL';
export const RESET_ACTIVITY_DESTINATION_LIST =
    'RESET_ACTIVITY_DESTINATION_LIST';
export const RESET_ACTIVITY_DESTINATION_DETAIL =
    'RESET_ACTIVITY_DESTINATION_DETAIL';
export const PERIOD_LIST = 'PERIOD_LIST';
export const ACCOMMODATION_LIST = 'ACCOMMODATION_LIST';
export const ESSENTIAL_TYPE_LIST = 'ESSENTIAL_TYPE_LIST';
export const MINING_TYPE_LIST = 'MINING_TYPE_LIST';
export const RETAIL_TYPE_LIST = 'RETAIL_TYPE_LIST';
export const TRANSPORT_TYPE_LIST = 'TRANSPORT_TYPE_LIST';
export const AD_VIDEO_LIST = 'AD_VIDEO_LIST';
export const RESET_HANDOVER_VIDEO = 'RESET_HANDOVER_VIDEO';
export const ADVERTISEMENT_LIST = 'ADVERTISEMENT_LIST';
export const FEATURED_ADVERTISEMENT_LIST = 'FEATURED_ADVERTISEMENT_LIST';
export const SPECIFC_ADS_RESTAURANT_LIST = 'SPECIFIC_ADS_RESTAURANT_LIST';
export const SPECIFIC_ADS_ACTIVITY_DESTINATION_LIST =
    'SPECIFIC_ADS_ACTIVITY_DESTINATION_LIST';
export const SPECIFIC_ADS_ESSENTIAL_LIST = 'SPECIFIC_ADS_ESSENTIAL_LIST';
export const SPECIFIC_ADS_MINING_LIST = 'SPECIFIC_ADS_MINING_LIST';
export const SPECIFIC_ADS_RETAIL_LIST = 'SPECIFIC_ADS_RETAIL_LIST';
export const SPECIFIC_ADS_TRANSPORT_LIST = 'SPECIFIC_ADS_TRANSPORT_LIST';
export const SPECIFIC_ADS_ACCOMMODATION_LIST =
    'SPECIFIC_ADS_ACCOMMODATION_LIST';
export const SPECIFIC_ADS_EVENT_LIST = 'SPECIFIC_ADS_EVENT_LIST';
export const RETRIEVE_HANDOVER_VIDEO = 'RETRIEVE_HANDOVER_VIDEO';
export const EVENT_LIST = 'EVENT_LIST';
export const AIRPORT_INFO = 'AIRPORT_INFO';
export const SEARCH_DOCUMENTS = 'SEARCH_DOCUMENTS';
